name: Continuous Integration

on: 
  pull_request: 
    branches: [ dev ]
  push:
    branches: ["dev-*"]

jobs: 
  analyze: 
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps: 
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.0.5'
          channel: 'stable'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: install dependencies
        continue-on-error: true
        run: cd App && flutter pub get
      - run: cd App && flutter analyze --fatal-infos --fatal-warnings .

  widget_test: 
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps: 
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with: 
          flutter-version: '3.0.5'
          channel: 'stable'
          cache: true
          cache-key: flutter # optional, change this to force refresh cache
          cache-path: ${{ runner.tool_cache }}/flutter
      - name: doctor
        continue-on-error: true
        run: cd App && flutter doctor -v
      - name: install dependencies
        continue-on-error: true
        run: cd App && flutter pub get
      - name: run test
        continue-on-error: true
        run: cd App && flutter test --coverage --coverage-path=./coverage/lcov.info
